service: Lambda-fun-deploy



provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  Front:
    handler: src/handler.hello

  Login:
    handler: src1/handler.hello1  
    
plugins:
    - serverless-webpack 

package:
    individually: true