service: Lambda-fun-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello3:
    handler: src3/handler.generateRandomNumber
    timeout: 60 # secondss
    memorySize: 128 # mb

  fast:
    runtime: python3.6
    events:
      - http:
          method: get
          path: greet
    handler: web/handler.hello

  time:
    runtime: nodejs6.10
    events:
      - http:
          method: get
          path: time
    handler: wev2/handler.timestamp

package:
 individually: true