service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb

  hello1:
    handler: src1/handler.hello
    timeout: 60 # seconds
    memorySize: 128 # mb

  hello2:
    handler: src2/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb 

package:
 individually: true