service: Lambda-fun-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: src/handler.hello

  app1:
    handler: src1/handler.hello1  
    
  
package:
 individually: true