service: Lambda-fun-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  Front:
    handler: Front/handler.hello

  Login:
    handler: Login/handler.hello1  
    
plugins:
    - serverless-webpack 

package:
    individually: true