service: Lambda-fun-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: src3/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'      
  
package:
 individually: true