service: Lambda-fun-deploy

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  hello123:
    handler: src/handler.hello
    timeout: 60 # seconds
    memorySize: 128 # mb  
  
package:
 individually: true